### ISSUE TITLE
Still boost is not correctly linked to Python inside the Anaconda environment

### ISSUE THREAD

**Issue by s0r2637** [menpo/conda-boost#3]
Hi,

I followed your instructions to manually build boost for specifically the Anaconda environment.  It seems it does not link to Python calls correctly. Could I get some help regarding that?

**Comment by patricksnape** [comment]
Can you use the boost from conda-forge? Boost is notoriously difficult to build

**Comment by s0r2637** [comment]
Thanks a lot!  That did it.  Now I can use applications in Python that needed boost libraries.  Thanks again!

**Comment by s0r2637** [comment]
Hi Patrick,
It seems that although boost from conda-forge fixed on of the boost problems, there is one more place the problem remains.  I am attaching the error below:

`Boost.Python.ArgumentError: Python argument types in
    Context.open_file_recording(Context, str)
did not match C++ signature:
    open_file_recording(xn::Context {lvalue}, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)`

It works fine outside of Conda, but I don't know what this error means.  Any help would be appreciated.

**Comment by s0r2637** [comment]
Btw.  I installed boost 1.5.9. from conda-forge

**Comment by patricksnape** [comment]
Sorry but I can't really debug this for you as I have no context about what you are trying to achieve, what your environment is or where that error is even coming from. I also don't know what "it works fine outside of conda" means?
